//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.12 at 02:45:59 PM EEST 
//


package eu.robopartner.ps.planner.planninginputmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NON_WORKING_PERIODS"/>
 *         &lt;element ref="{}FORCED_WORKING_PERIODS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nonworkingperiods",
    "forcedworkingperiods"
})
@XmlRootElement(name = "RESOURCE_AVAILABILITY")
public class RESOURCEAVAILABILITY {

    @XmlElement(name = "NON_WORKING_PERIODS", required = true)
    protected NONWORKINGPERIODS nonworkingperiods;
    @XmlElement(name = "FORCED_WORKING_PERIODS", required = true)
    protected FORCEDWORKINGPERIODS forcedworkingperiods;

    /**
     * Gets the value of the nonworkingperiods property.
     * 
     * @return
     *     possible object is
     *     {@link NONWORKINGPERIODS }
     *     
     */
    public NONWORKINGPERIODS getNONWORKINGPERIODS() {
        return nonworkingperiods;
    }

    /**
     * Sets the value of the nonworkingperiods property.
     * 
     * @param value
     *     allowed object is
     *     {@link NONWORKINGPERIODS }
     *     
     */
    public void setNONWORKINGPERIODS(NONWORKINGPERIODS value) {
        this.nonworkingperiods = value;
    }

    /**
     * Gets the value of the forcedworkingperiods property.
     * 
     * @return
     *     possible object is
     *     {@link FORCEDWORKINGPERIODS }
     *     
     */
    public FORCEDWORKINGPERIODS getFORCEDWORKINGPERIODS() {
        return forcedworkingperiods;
    }

    /**
     * Sets the value of the forcedworkingperiods property.
     * 
     * @param value
     *     allowed object is
     *     {@link FORCEDWORKINGPERIODS }
     *     
     */
    public void setFORCEDWORKINGPERIODS(FORCEDWORKINGPERIODS value) {
        this.forcedworkingperiods = value;
    }

}
