//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.12 at 02:45:59 PM EEST 
//

package eu.robopartner.ps.planner.planninginputmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}FROM_CODE"/>
 *         &lt;element ref="{}TO_CODE"/>
 *         &lt;element ref="{}TIME_IN_SECONDS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "fromcode", "tocode", "timeinseconds" })
@XmlRootElement(name = "SET_UP")
public class SETUP {

	@XmlElement(name = "FROM_CODE", required = true)
	protected String fromcode;
	@XmlElement(name = "TO_CODE", required = true)
	protected String tocode;
	@XmlElement(name = "TIME_IN_SECONDS")
	protected int timeinseconds;

	/**
	 * Gets the value of the fromcode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFROMCODE() {
		return fromcode;
	}

	/**
	 * Sets the value of the fromcode property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setFROMCODE(String value) {
		this.fromcode = value;
	}

	/**
	 * Gets the value of the tocode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTOCODE() {
		return tocode;
	}

	/**
	 * Sets the value of the tocode property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTOCODE(String value) {
		this.tocode = value;
	}

	/**
	 * Gets the value of the timeinseconds property.
	 * 
	 */
	public int getTIMEINSECONDS() {
		return timeinseconds;
	}

	/**
	 * Sets the value of the timeinseconds property.
	 * 
	 */
	public void setTIMEINSECONDS(int value) {
		this.timeinseconds = value;
	}

}
