//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.12 at 02:45:59 PM EEST 
//


package eu.robopartner.ps.planner.planninginputmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NAME"/>
 *         &lt;element ref="{}DESCRIPTION" minOccurs="0"/>
 *         &lt;element ref="{}SET_UP_MATRIX_REFERENCE" minOccurs="0"/>
 *         &lt;element ref="{}RESOURCE_AVAILABILITY" minOccurs="0"/>
 *         &lt;element ref="{}PROPERTIES" minOccurs="0"/>
 *         &lt;element ref="{}TOOL_TYPE_REFERENCE"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "description",
    "setupmatrixreference",
    "resourceavailability",
    "properties",
    "tooltypereference"
})
@XmlRootElement(name = "TOOL")
public class TOOL {

    @XmlElement(name = "NAME", required = true)
    protected String name;
    @XmlElement(name = "DESCRIPTION")
    protected String description;
    @XmlElement(name = "SET_UP_MATRIX_REFERENCE")
    protected SETUPMATRIXREFERENCE setupmatrixreference;
    @XmlElement(name = "RESOURCE_AVAILABILITY")
    protected RESOURCEAVAILABILITY resourceavailability;
    @XmlElement(name = "PROPERTIES")
    protected PROPERTIES properties;
    @XmlElement(name = "TOOL_TYPE_REFERENCE", required = true)
    protected TOOLTYPEREFERENCE tooltypereference;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the setupmatrixreference property.
     * 
     * @return
     *     possible object is
     *     {@link SETUPMATRIXREFERENCE }
     *     
     */
    public SETUPMATRIXREFERENCE getSETUPMATRIXREFERENCE() {
        return setupmatrixreference;
    }

    /**
     * Sets the value of the setupmatrixreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link SETUPMATRIXREFERENCE }
     *     
     */
    public void setSETUPMATRIXREFERENCE(SETUPMATRIXREFERENCE value) {
        this.setupmatrixreference = value;
    }

    /**
     * Gets the value of the resourceavailability property.
     * 
     * @return
     *     possible object is
     *     {@link RESOURCEAVAILABILITY }
     *     
     */
    public RESOURCEAVAILABILITY getRESOURCEAVAILABILITY() {
        return resourceavailability;
    }

    /**
     * Sets the value of the resourceavailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link RESOURCEAVAILABILITY }
     *     
     */
    public void setRESOURCEAVAILABILITY(RESOURCEAVAILABILITY value) {
        this.resourceavailability = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PROPERTIES }
     *     
     */
    public PROPERTIES getPROPERTIES() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROPERTIES }
     *     
     */
    public void setPROPERTIES(PROPERTIES value) {
        this.properties = value;
    }

    /**
     * Gets the value of the tooltypereference property.
     * 
     * @return
     *     possible object is
     *     {@link TOOLTYPEREFERENCE }
     *     
     */
    public TOOLTYPEREFERENCE getTOOLTYPEREFERENCE() {
        return tooltypereference;
    }

    /**
     * Sets the value of the tooltypereference property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOOLTYPEREFERENCE }
     *     
     */
    public void setTOOLTYPEREFERENCE(TOOLTYPEREFERENCE value) {
        this.tooltypereference = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
