//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.12 at 02:45:59 PM EEST 
//

package eu.robopartner.ps.planner.planninginputmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NAME"/>
 *         &lt;element ref="{}DESCRIPTION" minOccurs="0"/>
 *         &lt;element ref="{}ALGORITHM"/>
 *         &lt;element ref="{}WORKCENTER_RESOURCE_REFERENCE" maxOccurs="unbounded"/>
 *         &lt;element name="TOOL_REPOSITORY" type="{}TOOL_PLACEMENT" minOccurs="0"/>
 *         &lt;element ref="{}DOCKING_STATIONS" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "name", "description", "algorithm", "workcenterresourcereference", "toolrepository",
		"dockingstations" })
@XmlRootElement(name = "WORKCENTER")
public class WORKCENTER {

	@XmlElement(name = "NAME", required = true)
	protected String name;
	@XmlElement(name = "DESCRIPTION")
	protected String description;
	@XmlElement(name = "ALGORITHM", required = true)
	protected String algorithm;
	@XmlElement(name = "WORKCENTER_RESOURCE_REFERENCE", required = true)
	protected List<WORKCENTERRESOURCEREFERENCE> workcenterresourcereference;
	@XmlElement(name = "TOOL_REPOSITORY")
	protected TOOLPLACEMENT toolrepository;
	@XmlElement(name = "DOCKING_STATIONS")
	protected DOCKINGSTATIONS dockingstations;
	@XmlAttribute(name = "id", required = true)
	protected String id;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNAME() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setNAME(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDESCRIPTION() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setDESCRIPTION(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the algorithm property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getALGORITHM() {
		return algorithm;
	}

	/**
	 * Sets the value of the algorithm property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setALGORITHM(String value) {
		this.algorithm = value;
	}

	/**
	 * Gets the value of the workcenterresourcereference property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the workcenterresourcereference property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getWORKCENTERRESOURCEREFERENCE().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link WORKCENTERRESOURCEREFERENCE }
	 * 
	 * 
	 */
	public List<WORKCENTERRESOURCEREFERENCE> getWORKCENTERRESOURCEREFERENCE() {
		if (workcenterresourcereference == null) {
			workcenterresourcereference = new ArrayList<WORKCENTERRESOURCEREFERENCE>();
		}
		return this.workcenterresourcereference;
	}

	/**
	 * Gets the value of the toolrepository property.
	 * 
	 * @return possible object is {@link TOOLPLACEMENT }
	 * 
	 */
	public TOOLPLACEMENT getTOOLREPOSITORY() {
		return toolrepository;
	}

	/**
	 * Sets the value of the toolrepository property.
	 * 
	 * @param value allowed object is {@link TOOLPLACEMENT }
	 * 
	 */
	public void setTOOLREPOSITORY(TOOLPLACEMENT value) {
		this.toolrepository = value;
	}

	/**
	 * Gets the value of the dockingstations property.
	 * 
	 * @return possible object is {@link DOCKINGSTATIONS }
	 * 
	 */
	public DOCKINGSTATIONS getDOCKINGSTATIONS() {
		return dockingstations;
	}

	/**
	 * Sets the value of the dockingstations property.
	 * 
	 * @param value allowed object is {@link DOCKINGSTATIONS }
	 * 
	 */
	public void setDOCKINGSTATIONS(DOCKINGSTATIONS value) {
		this.dockingstations = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

}
