package hibernate;
// Generated Feb 6, 2019 3:37:35 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Assemblystation generated by hbm2java
 */
public class Assemblystation implements java.io.Serializable {

	private int id;
	private Integer idAssemblyStation;
	private String name;
	private String description;
	private String location;
	private Integer assemblyLineId;
	private Integer positionId;
	private Integer positionParametersId;
	private Integer positionResourecsId;
	private Integer positionResourecsElementsId;
	private Integer positionAssemblyLineId;
	private Set assemblylines = new HashSet(0);
	private Set workingareadbs = new HashSet(0);

	public Assemblystation() {
	}

	public Assemblystation(int id) {
		this.id = id;
	}

	public Assemblystation(int id, Integer idAssemblyStation, String name, String description, String location,
			Integer assemblyLineId, Integer positionId, Integer positionParametersId, Integer positionResourecsId,
			Integer positionResourecsElementsId, Integer positionAssemblyLineId, Set assemblylines,
			Set workingareadbs) {
		this.id = id;
		this.idAssemblyStation = idAssemblyStation;
		this.name = name;
		this.description = description;
		this.location = location;
		this.assemblyLineId = assemblyLineId;
		this.positionId = positionId;
		this.positionParametersId = positionParametersId;
		this.positionResourecsId = positionResourecsId;
		this.positionResourecsElementsId = positionResourecsElementsId;
		this.positionAssemblyLineId = positionAssemblyLineId;
		this.assemblylines = assemblylines;
		this.workingareadbs = workingareadbs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getIdAssemblyStation() {
		return this.idAssemblyStation;
	}

	public void setIdAssemblyStation(Integer idAssemblyStation) {
		this.idAssemblyStation = idAssemblyStation;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Integer getAssemblyLineId() {
		return this.assemblyLineId;
	}

	public void setAssemblyLineId(Integer assemblyLineId) {
		this.assemblyLineId = assemblyLineId;
	}

	public Integer getPositionId() {
		return this.positionId;
	}

	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}

	public Integer getPositionParametersId() {
		return this.positionParametersId;
	}

	public void setPositionParametersId(Integer positionParametersId) {
		this.positionParametersId = positionParametersId;
	}

	public Integer getPositionResourecsId() {
		return this.positionResourecsId;
	}

	public void setPositionResourecsId(Integer positionResourecsId) {
		this.positionResourecsId = positionResourecsId;
	}

	public Integer getPositionResourecsElementsId() {
		return this.positionResourecsElementsId;
	}

	public void setPositionResourecsElementsId(Integer positionResourecsElementsId) {
		this.positionResourecsElementsId = positionResourecsElementsId;
	}

	public Integer getPositionAssemblyLineId() {
		return this.positionAssemblyLineId;
	}

	public void setPositionAssemblyLineId(Integer positionAssemblyLineId) {
		this.positionAssemblyLineId = positionAssemblyLineId;
	}

	public Set getAssemblylines() {
		return this.assemblylines;
	}

	public void setAssemblylines(Set assemblylines) {
		this.assemblylines = assemblylines;
	}

	public Set getWorkingareadbs() {
		return this.workingareadbs;
	}

	public void setWorkingareadbs(Set workingareadbs) {
		this.workingareadbs = workingareadbs;
	}

}
