package hibernate;
// Generated Jan 25, 2019 5:59:11 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Assemblyline generated by hbm2java
 */
public class Assemblyline implements java.io.Serializable {

	private int id;
	private Integer idAssemblyLine;
	private String name;
	private String description;
	private String location;
	private Set shopfloors = new HashSet(0);
	private Set assemblystations = new HashSet(0);

	public Assemblyline() {
	}

	public Assemblyline(int id) {
		this.id = id;
	}

	public Assemblyline(int id, Integer idAssemblyLine, String name, String description, String location,
			Set shopfloors, Set assemblystations) {
		this.id = id;
		this.idAssemblyLine = idAssemblyLine;
		this.name = name;
		this.description = description;
		this.location = location;
		this.shopfloors = shopfloors;
		this.assemblystations = assemblystations;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getIdAssemblyLine() {
		return this.idAssemblyLine;
	}

	public void setIdAssemblyLine(Integer idAssemblyLine) {
		this.idAssemblyLine = idAssemblyLine;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Set getShopfloors() {
		return this.shopfloors;
	}

	public void setShopfloors(Set shopfloors) {
		this.shopfloors = shopfloors;
	}

	public Set getAssemblystations() {
		return this.assemblystations;
	}

	public void setAssemblystations(Set assemblystations) {
		this.assemblystations = assemblystations;
	}

}
