package hibernate;
// Generated Feb 6, 2019 3:37:35 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Elements generated by hbm2java
 */
public class Elements implements java.io.Serializable {

	private int id;
	private Set resourcesdbs = new HashSet(0);
	private Set sensorses = new HashSet(0);
	private Set toolsdbs = new HashSet(0);

	public Elements() {
	}

	public Elements(int id) {
		this.id = id;
	}

	public Elements(int id, Set resourcesdbs, Set sensorses, Set toolsdbs) {
		this.id = id;
		this.resourcesdbs = resourcesdbs;
		this.sensorses = sensorses;
		this.toolsdbs = toolsdbs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Set getResourcesdbs() {
		return this.resourcesdbs;
	}

	public void setResourcesdbs(Set resourcesdbs) {
		this.resourcesdbs = resourcesdbs;
	}

	public Set getSensorses() {
		return this.sensorses;
	}

	public void setSensorses(Set sensorses) {
		this.sensorses = sensorses;
	}

	public Set getToolsdbs() {
		return this.toolsdbs;
	}

	public void setToolsdbs(Set toolsdbs) {
		this.toolsdbs = toolsdbs;
	}

}
