package hibernate;
// Generated Feb 6, 2019 3:37:35 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Parametersdb generated by hbm2java
 */
public class Parametersdb implements java.io.Serializable {

	private int id;
	private String type;
	private String value;
	private String description;
	private Set actionsdbs = new HashSet(0);

	public Parametersdb() {
	}

	public Parametersdb(int id) {
		this.id = id;
	}

	public Parametersdb(int id, String type, String value, String description, Set actionsdbs) {
		this.id = id;
		this.type = type;
		this.value = value;
		this.description = description;
		this.actionsdbs = actionsdbs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getActionsdbs() {
		return this.actionsdbs;
	}

	public void setActionsdbs(Set actionsdbs) {
		this.actionsdbs = actionsdbs;
	}

}
