package hibernate;
// Generated Feb 6, 2019 3:37:35 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Part generated by hbm2java
 */
public class Part implements java.io.Serializable {

	private int id;
	private Workingareadb workingareadb;
	private Double weight;
	private String type;
	private String name;
	private String workingArea;
	private Set operationsdbs = new HashSet(0);

	public Part() {
	}

	public Part(int id) {
		this.id = id;
	}

	public Part(int id, Workingareadb workingareadb, Double weight, String type, String name, String workingArea,
			Set operationsdbs) {
		this.id = id;
		this.workingareadb = workingareadb;
		this.weight = weight;
		this.type = type;
		this.name = name;
		this.workingArea = workingArea;
		this.operationsdbs = operationsdbs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Workingareadb getWorkingareadb() {
		return this.workingareadb;
	}

	public void setWorkingareadb(Workingareadb workingareadb) {
		this.workingareadb = workingareadb;
	}

	public Double getWeight() {
		return this.weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getWorkingArea() {
		return this.workingArea;
	}

	public void setWorkingArea(String workingArea) {
		this.workingArea = workingArea;
	}

	public Set getOperationsdbs() {
		return this.operationsdbs;
	}

	public void setOperationsdbs(Set operationsdbs) {
		this.operationsdbs = operationsdbs;
	}

}
