package hibernate;
// Generated Jan 24, 2019 3:46:58 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Processsdb generated by hbm2java
 */
public class Processsdb implements java.io.Serializable {

	private int id;
	private Set tasksdbs = new HashSet(0);

	public Processsdb() {
	}

	public Processsdb(int id) {
		this.id = id;
	}

	public Processsdb(int id, Set tasksdbs) {
		this.id = id;
		this.tasksdbs = tasksdbs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Set getTasksdbs() {
		return this.tasksdbs;
	}

	public void setTasksdbs(Set tasksdbs) {
		this.tasksdbs = tasksdbs;
	}

}
