package hibernate;
// Generated Jan 25, 2019 4:02:57 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Shopfloor generated by hbm2java
 */
public class Shopfloor implements java.io.Serializable {

	private int id;
	private Integer shopfloorId;
	private String name;
	private String description;
	private Integer assemblyLineId;
	private Set assemblylines = new HashSet(0);

	public Shopfloor() {
	}

	public Shopfloor(int id) {
		this.id = id;
	}

	public Shopfloor(int id, Integer shopfloorId, String name, String description, Integer assemblyLineId,
			Set assemblylines) {
		this.id = id;
		this.shopfloorId = shopfloorId;
		this.name = name;
		this.description = description;
		this.assemblyLineId = assemblyLineId;
		this.assemblylines = assemblylines;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getShopfloorId() {
		return this.shopfloorId;
	}

	public void setShopfloorId(Integer shopfloorId) {
		this.shopfloorId = shopfloorId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getAssemblyLineId() {
		return this.assemblyLineId;
	}

	public void setAssemblyLineId(Integer assemblyLineId) {
		this.assemblyLineId = assemblyLineId;
	}

	public Set getAssemblylines() {
		return this.assemblylines;
	}

	public void setAssemblylines(Set assemblylines) {
		this.assemblylines = assemblylines;
	}

}
