package hibernate;
// Generated Jan 25, 2019 4:02:57 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Toolparameters generated by hbm2java
 */
public class Toolparameters implements java.io.Serializable {

	private int id;
	private String value;
	private String name;
	private String description;
	private String arg;
	private String type;
	private Set toolsdbs = new HashSet(0);

	public Toolparameters() {
	}

	public Toolparameters(int id) {
		this.id = id;
	}

	public Toolparameters(int id, String value, String name, String description, String arg, String type,
			Set toolsdbs) {
		this.id = id;
		this.value = value;
		this.name = name;
		this.description = description;
		this.arg = arg;
		this.type = type;
		this.toolsdbs = toolsdbs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getArg() {
		return this.arg;
	}

	public void setArg(String arg) {
		this.arg = arg;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getToolsdbs() {
		return this.toolsdbs;
	}

	public void setToolsdbs(Set toolsdbs) {
		this.toolsdbs = toolsdbs;
	}

}
