package hibernate;
// Generated Jan 24, 2019 3:45:47 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tools generated by hbm2java
 */
public class Tools implements java.io.Serializable {

	private int id;
	private Elements elements;
	private Set toolparameterses = new HashSet(0);
	private Set operationsdbs = new HashSet(0);

	public Tools() {
	}

	public Tools(int id) {
		this.id = id;
	}

	public Tools(int id, Elements elements, Set toolparameterses, Set operationsdbs) {
		this.id = id;
		this.elements = elements;
		this.toolparameterses = toolparameterses;
		this.operationsdbs = operationsdbs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Elements getElements() {
		return this.elements;
	}

	public void setElements(Elements elements) {
		this.elements = elements;
	}

	public Set getToolparameterses() {
		return this.toolparameterses;
	}

	public void setToolparameterses(Set toolparameterses) {
		this.toolparameterses = toolparameterses;
	}

	public Set getOperationsdbs() {
		return this.operationsdbs;
	}

	public void setOperationsdbs(Set operationsdbs) {
		this.operationsdbs = operationsdbs;
	}

}
