package hibernate;
// Generated Jan 25, 2019 4:02:57 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Toolsdb generated by hbm2java
 */
public class Toolsdb implements java.io.Serializable {

	private int id;
	private Elements elements;
	private Tooltype tooltype;
	private Set toolparameterses = new HashSet(0);
	private Set operationsdbs = new HashSet(0);
	private Set resourcesdbs = new HashSet(0);

	public Toolsdb() {
	}

	public Toolsdb(int id) {
		this.id = id;
	}

	public Toolsdb(int id, Elements elements, Tooltype tooltype, Set toolparameterses, Set operationsdbs,
			Set resourcesdbs) {
		this.id = id;
		this.elements = elements;
		this.tooltype = tooltype;
		this.toolparameterses = toolparameterses;
		this.operationsdbs = operationsdbs;
		this.resourcesdbs = resourcesdbs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Elements getElements() {
		return this.elements;
	}

	public void setElements(Elements elements) {
		this.elements = elements;
	}

	public Tooltype getTooltype() {
		return this.tooltype;
	}

	public void setTooltype(Tooltype tooltype) {
		this.tooltype = tooltype;
	}

	public Set getToolparameterses() {
		return this.toolparameterses;
	}

	public void setToolparameterses(Set toolparameterses) {
		this.toolparameterses = toolparameterses;
	}

	public Set getOperationsdbs() {
		return this.operationsdbs;
	}

	public void setOperationsdbs(Set operationsdbs) {
		this.operationsdbs = operationsdbs;
	}

	public Set getResourcesdbs() {
		return this.resourcesdbs;
	}

	public void setResourcesdbs(Set resourcesdbs) {
		this.resourcesdbs = resourcesdbs;
	}

}
