package hibernate;
// Generated Jan 25, 2019 5:59:11 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Workingareadb generated by hbm2java
 */
public class Workingareadb implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private String location;
	private Set operationsdbs = new HashSet(0);
	private Set parts = new HashSet(0);
	private Set assemblystations = new HashSet(0);
	private Set resourcesdbs = new HashSet(0);

	public Workingareadb() {
	}

	public Workingareadb(int id) {
		this.id = id;
	}

	public Workingareadb(int id, String name, String description, String location, Set operationsdbs, Set parts,
			Set assemblystations, Set resourcesdbs) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.location = location;
		this.operationsdbs = operationsdbs;
		this.parts = parts;
		this.assemblystations = assemblystations;
		this.resourcesdbs = resourcesdbs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Set getOperationsdbs() {
		return this.operationsdbs;
	}

	public void setOperationsdbs(Set operationsdbs) {
		this.operationsdbs = operationsdbs;
	}

	public Set getParts() {
		return this.parts;
	}

	public void setParts(Set parts) {
		this.parts = parts;
	}

	public Set getAssemblystations() {
		return this.assemblystations;
	}

	public void setAssemblystations(Set assemblystations) {
		this.assemblystations = assemblystations;
	}

	public Set getResourcesdbs() {
		return this.resourcesdbs;
	}

	public void setResourcesdbs(Set resourcesdbs) {
		this.resourcesdbs = resourcesdbs;
	}

}
