package model;
// Generated Jan 18, 2019 2:05:02 PM by Hibernate Tools 5.3.6.Final

/**
 * Employee1 generated by hbm2java
 */
public class Employee1 implements java.io.Serializable {

	private int id;
	private int Operations_id;
	private int el_id;
	private String material;
	private int maxDimension;
	private String partscol;
	private int stifness;
	private int weight;

	public Employee1() {
	}

	public Employee1(int id) {
		this.id = id;
	}

	public Employee1(int id, int Operations_id, int el_id, String material, int maxDimension, String partscol,
			int stifness, int weight) {
		this.id = id;
		this.Operations_id = Operations_id;
		this.el_id = el_id;
		this.material = material;
		this.maxDimension = maxDimension;
		this.partscol = partscol;
		this.stifness = stifness;
		this.weight = weight;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getOperations_id() {
		return this.Operations_id;
	}

	public void setOperations_id(int Operations_id) {
		this.Operations_id = Operations_id;
	}

	public int getEl_id() {
		return this.el_id;
	}

	public void setEl_id(int el_id) {
		this.el_id = el_id;
	}

	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	public int getMaxDimension() {
		return this.maxDimension;
	}

	public void setMaxDimension(int maxDimension) {
		this.maxDimension = maxDimension;
	}

	public String getPartscol() {
		return this.partscol;
	}

	public void setPartscol(String partscol) {
		this.partscol = partscol;
	}

	public int getStifness() {
		return this.stifness;
	}

	public void setStifness(int stifness) {
		this.stifness = stifness;
	}

	public int getWeight() {
		return this.weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

}
